In [1]:
import sys
sys.path.append('../') # or just install the module
sys.path.append('../../fuzzy-torch') # or just install the module
sys.path.append('../../fuzzy-tools') # or just install the module
sys.path.append('../../astro-lightcurves-handler') # or just install the module

In [19]:
%load_ext autoreload
%autoreload 2
from sklearn.preprocessing import QuantileTransformer, StandardScaler
from sklearn.decomposition import PCA, KernelPCA, FastICA
from sklearn.manifold import TSNE
from umap import UMAP
from fuzzytools.datascience.dim_reductors import DimReductor
import numpy as np

random_state = 0
n = 1000
x = np.random.uniform(0, .1, size=(n,100))
scaler = StandardScaler()
red_map = UMAP(
    n_components=2,
    metric='euclidean',
    n_neighbors=int(5),
    min_dist=.01,
    random_state=random_state,
    transform_seed=random_state,
    )
dim_reductor = DimReductor(scaler, red_map,
    inter_pca_dims=10,
    )
dim_reductor.fit(x)
z = dim_reductor.transform(x)
z

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


array([[ 5.0131273,  4.2808456],
       [ 5.623949 ,  4.483803 ],
       [10.524104 ,  3.2499943],
       ...,
       [ 5.6450214,  3.4948657],
       [ 8.546334 ,  5.7055   ],
       [ 6.046563 ,  1.2429343]], dtype=float32)

In [22]:
z = dim_reductor.transform(x)
z

array([[ 5.0131273,  4.2808456],
       [ 5.623949 ,  4.483803 ],
       [10.524104 ,  3.2499943],
       ...,
       [ 5.6450214,  3.4948657],
       [ 8.546334 ,  5.7055   ],
       [ 6.046563 ,  1.2429343]], dtype=float32)

In [14]:
z = dim_reductor.transform(x)
z

array([[ 1.338856  ,  0.3970636 ],
       [ 1.4447285 , -1.3986973 ],
       [ 2.4044805 , -0.55716753],
       ...,
       [ 5.4601035 ,  1.3505667 ],
       [ 1.2954812 , -1.5399494 ],
       [ 4.5559998 , -0.39022884]], dtype=float32)